import { Audio } from 'expo-av';
import * as Speech from 'expo-speech';
import { useCallback, useEffect, useRef } from 'react';
import { AUDIO_FILES } from '../data/audioFiles';

// AUDIO_FILES is auto-generated by scripts/generate-audio.py.
// When empty, every call falls back to expo-speech browser TTS.
// When populated, the matching MP3 is played via expo-av instead.

const ALBANIAN_LANG = 'sq-AL';
const FALLBACK_LANG = 'sq';

export function useSpeech() {
  const isMounted = useRef(true);
  const currentSound = useRef<Audio.Sound | null>(null);

  useEffect(() => {
    Audio.setAudioModeAsync({ playsInSilentModeIOS: true }).catch(() => {});
    return () => { isMounted.current = false; };
  }, []);

  const stop = useCallback(() => {
    currentSound.current?.stopAsync().catch(() => {});
    Speech.stop();
  }, []);

  const speak = useCallback((text: string, rate = 0.85) => {
    stop();
    const asset = AUDIO_FILES[text];
    if (asset !== undefined) {
      Audio.Sound.createAsync(asset)
        .then(({ sound }) => {
          currentSound.current = sound;
          sound.playAsync();
          sound.setOnPlaybackStatusUpdate((status) => {
            if ('didJustFinish' in status && status.didJustFinish) {
              sound.unloadAsync().catch(() => {});
            }
          });
        })
        .catch(() => {
          Speech.speak(text, { language: ALBANIAN_LANG, rate, pitch: 1.1 });
        });
    } else {
      Speech.speak(text, {
        language: ALBANIAN_LANG,
        rate,
        pitch: 1.1,
        onError: () => {
          Speech.speak(text, { language: FALLBACK_LANG, rate, pitch: 1.1 });
        },
      });
    }
  }, [stop]);

  const speakSlow = useCallback((text: string) => speak(text, 0.65), [speak]);

  const praise = useCallback((name?: string) => {
    const asset = AUDIO_FILES['Bravo!'];
    if (asset !== undefined) {
      Audio.Sound.createAsync(asset).then(({ sound }) => {
        sound.playAsync();
        sound.setOnPlaybackStatusUpdate((status) => {
          if ('didJustFinish' in status && status.didJustFinish) {
            sound.unloadAsync().catch(() => {});
          }
        });
      }).catch(() => {});
    } else {
      const phrases = [
        'Bravo!',
        name ? `Bravo, ${name}!` : 'Bravo!',
        'Shumë mirë!',
        'Shkëlqyeshëm!',
      ];
      speak(phrases[Math.floor(Math.random() * phrases.length)], 1.0);
    }
  }, [speak]);

  return { speak, speakSlow, stop, praise };
}
