"""
Albanian Adventures — Audio Generator (Meta MMS-TTS)
Uses facebook/mms-tts-sqi running locally on GPU (no API key needed).

Run from the Game/ directory:
    docker compose --profile audio run --rm generate-audio

The model (~400 MB) is downloaded on first run and cached in the hf-cache volume.
Generated MP3s land in assets/audio/{words,sentences,praises}/.
"""

import io
import os
import sys

import numpy as np
import scipy.io.wavfile
import torch
from pydub import AudioSegment
from transformers import AutoTokenizer, VitsModel

MODEL_ID = "facebook/mms-tts-sqi"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
BASE = os.path.join(os.path.dirname(__file__), "..", "assets", "audio")

# Keys are the output filename (no extension).
# Values are the Albanian text to synthesize.
# Word keys must match the `albanian` field in src/data/vocabulary.ts exactly.

WORDS = {
    # Animals
    "mace":         "mace",
    "qen":          "qen",
    "lope":         "lopë",
    "peshk":        "peshk",
    "zog":          "zog",
    "ari":          "ari",
    "kale":         "kalë",
    "bretkose":     "bretkosë",
    # Fruit
    "molle":        "mollë",
    "portokall":    "portokall",
    "banane":       "banane",
    "rrush":        "rrush",
    "dredhëz":      "dredhëz",
    "shalqi":       "shalqi",
    "qershi":       "qershi",
    # Colors
    "kuq":          "kuq",
    "gjelber":      "gjelbër",
    "kalter":       "kaltër",
    "verdhe":       "verdhë",
    "vjollce":      "vjollcë",
    "portokalli":   "portokalli",
    # Family
    "nene":         "nënë",
    "baba":         "baba",
    "vella":        "vëlla",
    "moter":        "motër",
    "gjyshe":       "gjyshë",
    "gjysh":        "gjysh",
}

SENTENCES = {
    "cat-milk":      "Macja pi qumësht",
    "boy-football":  "Djali luan futboll",
    "girl-book":     "Vajza lexon librin",
    "dog-meat":      "Qeni ha mishin",
    "mom-cooks":     "Nëna gatuan darkën",
    "dad-tv":        "Babi shikon televizorin",
    "kids-park":     "Fëmijët luajnë në park",
    "i-want-apple":  "Unë dua mollë",
    "you-are-good":  "Ti je i mirë",
    "we-go-school":  "Ne shkojmë në shkollë",
}

praises = {
    "bravo":         "Bravo!",
    "sakte":         "Saktë!",
    "provo-perseri": "Provo përsëri!",
    "hajde":         "Hajde!",
    "degjo":         "Dëgjoje",
}


def synth(model: VitsModel, tokenizer: AutoTokenizer, text: str, out_path: str) -> None:
    if os.path.exists(out_path):
        print(f"  skip  {os.path.basename(out_path)}")
        return
    inputs = tokenizer(text, return_tensors="pt").to(DEVICE)
    with torch.no_grad():
        waveform = model(**inputs).waveform[0].cpu().numpy()

    waveform_int16 = (np.clip(waveform, -1.0, 1.0) * 32767).astype(np.int16)
    wav_buf = io.BytesIO()
    scipy.io.wavfile.write(wav_buf, rate=model.config.sampling_rate, data=waveform_int16)
    wav_buf.seek(0)
    AudioSegment.from_wav(wav_buf).export(out_path, format="mp3", bitrate="96k")

    size = os.path.getsize(out_path)
    print(f"  ok    {os.path.basename(out_path)}  ({size // 1024} KB)")


def write_audio_files_ts() -> None:
    """Write src/data/audioFiles.ts with require() entries for every generated MP3."""
    ts_path = os.path.join(os.path.dirname(__file__), "..", "src", "data", "audioFiles.ts")
    lines = [
        "// Auto-generated by scripts/generate-audio.py — do not edit manually.",
        "// Run: docker compose --profile audio run --rm generate-audio",
        "// Then rebuild: docker compose exec game npm run build:web",
        "export const AUDIO_FILES: Record<string, number> = {",
    ]
    mapping = [
        ("words",     WORDS),
        ("sentences", SENTENCES),
        ("praises",   praises),
    ]
    for subdir, items in mapping:
        for file_id, text in items.items():
            mp3 = os.path.join(BASE, subdir, f"{file_id}.mp3")
            if os.path.exists(mp3):
                escaped = text.replace("'", "\\'")
                lines.append(f"  '{escaped}': require('../../assets/audio/{subdir}/{file_id}.mp3'),")
    lines.append("};")
    with open(ts_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  wrote  src/data/audioFiles.ts  ({len(lines) - 4} entries)")


def main() -> None:
    print(f"Device: {DEVICE}")
    if DEVICE == "cpu":
        print("WARNING: No GPU detected — generation will be slow.")

    print(f"Loading {MODEL_ID} ...")
    model = VitsModel.from_pretrained(MODEL_ID).to(DEVICE)
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
    model.eval()
    print("Model ready.\n")

    sections = [("words", WORDS), ("sentences", SENTENCES), ("praises", praises)]
    for subdir, items in sections:
        label = subdir.capitalize()
        print(f"── {label} {'─' * (38 - len(label))}")
        out_dir = os.path.join(BASE, subdir)
        os.makedirs(out_dir, exist_ok=True)
        for file_id, text in items.items():
            synth(model, tokenizer, text, os.path.join(out_dir, f"{file_id}.mp3"))

    print("\n── audioFiles.ts ──────────────────────────")
    write_audio_files_ts()
    print("\nDone. Rebuild the web bundle: docker compose exec game npm run build:web")


if __name__ == "__main__":
    main()
