#!/usr/bin/env node
/**
 * Scans assets/audio/{words,sentences,praises} and generates src/data/audioFiles.ts.
 *
 * Filename convention (required for auto-detection):
 *   Albanian text normalized: lowercase, ë→w, ç→c, spaces→hyphens, punctuation removed.
 *   Examples:
 *     lopë       → lopw.mp3
 *     në         → new.wav       (vs ne.wav for "ne")
 *     e gjelbër  → e-gjelbwr.mp3
 *     Macja pi qumësht → macja-pi-qumwsht.wav
 *
 * When both .mp3 and .wav exist for the same stem, WAV is preferred.
 * Non-audio files (e.g. .ts) are ignored.
 *
 * Usage:  node scripts/sync-audio.js   (or: npm run sync-audio)
 */
const fs = require('fs');
const path = require('path');

const AUDIO_BASE = path.join(__dirname, '..', 'assets', 'audio');
const OUTPUT = path.join(__dirname, '..', 'src', 'data', 'audioFiles.ts');

// Preference order for same-stem duplicates: later index wins.
const EXT_PRIORITY = ['.mp3', '.wav'];

function scanDir(dirName) {
  const dir = path.join(AUDIO_BASE, dirName);
  if (!fs.existsSync(dir)) return new Map();

  const byKey = new Map(); // key → { file, ext, priority }
  for (const f of fs.readdirSync(dir).sort()) {
    const ext = path.extname(f).toLowerCase();
    if (!EXT_PRIORITY.includes(ext)) continue;

    const key = path.basename(f, ext);
    const priority = EXT_PRIORITY.indexOf(ext);
    const existing = byKey.get(key);
    if (!existing || priority > existing.priority) {
      byKey.set(key, { file: f, dir: dirName, priority });
    }
  }
  return byKey;
}

const wordMap     = scanDir('words');
const sentenceMap = scanDir('sentences');
const phraseMap   = scanDir('praises');

// Merge all maps; sentences/praises can override words if keys overlap.
const allEntries = [];
for (const [key, { file, dir }] of wordMap)     allEntries.push({ key, file, dir });
for (const [key, { file, dir }] of sentenceMap) allEntries.push({ key, file, dir });
for (const [key, { file, dir }] of phraseMap)   allEntries.push({ key, file, dir });

if (allEntries.length === 0) {
  console.warn('No audio files found. Check assets/audio/ directory.');
  process.exit(0);
}

const lines = allEntries.map(({ key, file, dir }) =>
  `  '${key}': require('../../assets/audio/${dir}/${file}'),`
).join('\n');

const output = `// Auto-generated by scripts/sync-audio.js — do not edit manually.
// Run:  npm run sync-audio   (then rebuild the app)
//
// Key convention — normalize Albanian text with normalizeAudioKey() in useSpeech.ts:
//   ë → w  |  ç → c  |  spaces → hyphens  |  lowercase  |  no punctuation
export const AUDIO_FILES: Record<string, number> = {
${lines}
};
`;

// Write via temp file + rename to guarantee atomic replace (avoids partial-write artifacts).
const tmp = OUTPUT + '.tmp';
fs.writeFileSync(tmp, output, 'utf-8');
fs.renameSync(tmp, OUTPUT);
console.log(`✓ Generated ${allEntries.length} audio entries → src/data/audioFiles.ts`);
