// Auto-generated by scripts/generate-audio.py — do not edit manually.
// Run: docker compose --profile audio run --rm generate-audio
// Then rebuild: docker compose up --build -d
export const AUDIO_FILES: Record<string, number> = {
  // Animals
  'mace':     require('../../assets/audio/words/mace.mp3'),
  'qen':      require('../../assets/audio/words/qen.mp3'),
  'lopë':     require('../../assets/audio/words/lope.mp3'),
  'peshk':    require('../../assets/audio/words/peshk.mp3'),
  'zog':      require('../../assets/audio/words/zog.mp3'),
  'kalë':     require('../../assets/audio/words/kale.mp3'),
  'bretkosë': require('../../assets/audio/words/bretkose.mp3'),
  // 'ari': no recording yet

  // Fruit
  'mollë':    require('../../assets/audio/words/molle.mp3'),
  'portokall':require('../../assets/audio/words/portokall.mp3'),
  'banane':   require('../../assets/audio/words/banane.mp3'),
  'rrush':    require('../../assets/audio/words/rrush.mp3'),
  'dredhëz':  require('../../assets/audio/words/dredhez.mp3'),
  'shalqi':   require('../../assets/audio/words/shalqi.mp3'),
  'qershi':   require('../../assets/audio/words/qershi.mp3'),

  // Colors
  'kuq':        require('../../assets/audio/words/e-kuqe.mp3'),
  'gjelbër':    require('../../assets/audio/words/gjelber.mp3'),
  'kaltër':     require('../../assets/audio/words/kalter.mp3'),
  'verdhë':     require('../../assets/audio/words/verdhe.mp3'),
  'vjollcë':    require('../../assets/audio/words/vjollce.mp3'),
  'portokalli': require('../../assets/audio/words/e-portokall.mp3'),

  // Family
  'baba':  require('../../assets/audio/words/baba.mp3'),
  'vëlla': require('../../assets/audio/words/vellai.mp3'),
  'motër': require('../../assets/audio/words/motra.mp3'),
  'gjyshë':require('../../assets/audio/words/gjyshja.mp3'),
  'gjysh': require('../../assets/audio/words/gjyshi.mp3'),
  // 'nënë': no recording yet

  // Phrases
  'Bravo!': require('../../assets/audio/words/bravo.mp3'),
};
